#!/bin/bash

echo "Escriu una paraula"
read paraula
while [ $paraula != "q" ] 
do
	echo $paraula >> out.txt
	sort out.txt > Aux.txt
	mv Aux.txt out.txt
	echo "Escriu una paraula" 
	read paraula
done
cat out.txt
